# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: lorisleiva/laravel-docker:8.0

pipelines:
  branches:
    master:
      - step:
          name: (Pretend) Unit Testing
          caches:
            - composer
            - cposer
            - node
          script:
            - composer config bitbucket-oauth.bitbucket.org $BITBUCKET_CLIENT $BITBUCKET_SECRET
            - composer config -g github-oauth.github.com 235902933cf6ad227b534e7bf60decae368f8ea8
            - composer install --no-interaction --prefer-dist  --optimize-autoloader --no-dev
            - php artisan config:clear
            - php artisan event-sourcing:clear-event-handlers
      - step:
          name: Deploy to Production
          caches:
            - composer
            - cposer
            - node
            - vapor
          deployment: production
          trigger: manual
          script:
            - composer config bitbucket-oauth.bitbucket.org $BITBUCKET_CLIENT $BITBUCKET_SECRET
            - composer config -g github-oauth.github.com 235902933cf6ad227b534e7bf60decae368f8ea8
            - ln -f -s .env.example .env
            - composer install --no-interaction --prefer-dist  --optimize-autoloader --no-dev
            - npm install && npm run prod
            - php artisan config:clear
            - php artisan event-sourcing:clear-event-handlers
            - vendor/bin/vapor deploy production
    staging:
      - step:
          name: Deploy To Staging
          caches:
            - composer
            - cposer
            - node
            - vapor
            - docker
          deployment: staging
          script:
            - composer config bitbucket-oauth.bitbucket.org $BITBUCKET_CLIENT $BITBUCKET_SECRET
            - composer config -g github-oauth.github.com 235902933cf6ad227b534e7bf60decae368f8ea8
            - composer install --no-interaction --prefer-dist  --optimize-autoloader
            - npm install && npm run dev
            - php artisan config:clear
            - vendor/bin/vapor deploy staging
          services:
            - docker
    develop:
      - step:
          name: Deploy To develop
          caches:
            - composer
            - cposer
            - node
            - vapor
            - docker
          deployment: testing
          script:
            - composer config bitbucket-oauth.bitbucket.org $BITBUCKET_CLIENT $BITBUCKET_SECRET
            - composer config -g github-oauth.github.com 235902933cf6ad227b534e7bf60decae368f8ea8
            - composer install --no-interaction --prefer-dist  --optimize-autoloader
            - npm install && npm run dev
            - php artisan config:clear
            - vendor/bin/vapor deploy develop
          services:
            - docker
definitions:
  services:
    docker:
      memory: 1024
  caches:
    vapor: .vapor
    cposer: vendor

